name: validate-fhir-resources

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions: read-all

jobs:
  validate-fhir-resource:
    name: Validate FHIR resources
    runs-on: ubuntu-22.04
    container: ghcr.io/miracum/ig-build-tools:v2.0.51@sha256:a074f65655a343656214404769ed1ee21de5afd29073913c81f3b7f60290d552
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Firely.Terminal
        run: |
          dotnet tool install --global Firely.Terminal --version 3.1.0
          fhir --help

      - name: Restore FHIR package dependencies
        run: |
          fhir restore

      - name: Validate generated FHIR resources
        # TODO: switch to 'xargs' or for loop so if any validation fails, the entire command fails.
        # for fhir_file in src/test/java/snapshots/**/*.fhir.json; do fhir validate --verbose --fail "$fhir_file"; done
        run: |
          find src/test/java/snapshots -name "*.fhir.json" -exec fhir validate --verbose --fail "{}" \;
